/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.laliga.vista;

import com.laliga.controlador.LigaControlador;
import com.laliga.modelo.Jugador;
import com.laliga.dao.JugadorDAO;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author leire.domsan
 */
public class FormularioJugador extends javax.swing.JDialog {

    private JTextField txtNombre, txtPosicion, txtDorsal, txtNacionalidad;
    private JComboBox<Integer> comboEquipo; // Desplegable para el ID del equipo
    private JButton btnGuardar;
    /**
     * Creates new form FormularioJugador
     */
    public FormularioJugador(JFrame parent) {
        super(parent, "Fichar Nuevo Jugador", true);
        setSize(350, 300);
        setLocationRelativeTo(parent);
        
        // 6 filas (Nombre, Posición, Dorsal, Nacionalidad, Equipo, Botón)
        setLayout(new GridLayout(6, 2, 10, 10));

        add(new JLabel("  Nombre:"));
        txtNombre = new JTextField();
        add(txtNombre);

        add(new JLabel("  Posición:"));
        txtPosicion = new JTextField();
        add(txtPosicion);

        add(new JLabel("  Dorsal:"));
        txtDorsal = new JTextField();
        add(txtDorsal);

        add(new JLabel("  Nacionalidad:"));
        txtNacionalidad = new JTextField();
        add(txtNacionalidad);

        add(new JLabel("  ID Equipo:"));
        Integer[] equiposSimulados = {1, 2, 3}; // Luego esto vendrá de la BD
        comboEquipo = new JComboBox<>(equiposSimulados);
        add(comboEquipo);

        btnGuardar = new JButton("Confirmar Fichaje");
        add(new JLabel("")); // Espacio vacío
        add(btnGuardar);

        btnGuardar.addActionListener(e -> guardar());
    }

    private void guardar() {
        try {
            String nombre = txtNombre.getText();
            String posicion = txtPosicion.getText();
            int dorsal = Integer.parseInt(txtDorsal.getText());
            String nacionalidad = txtNacionalidad.getText();
            int idEquipo = (Integer) comboEquipo.getSelectedItem();

            //USAMOS EL CONTROLADOR
            if (!LigaControlador.validarJugador(nombre, posicion, dorsal, nacionalidad)) {
                return; // Si no es válido, paramos aquí y no llamamos al DAO
            }
            // 1. Recogemos los datos
            Jugador j = new Jugador();
            j.setNombre(txtNombre.getText());
            j.setPosicion(txtPosicion.getText());
            j.setDorsal(Integer.parseInt(txtDorsal.getText()));
            j.setNacionalidad(txtNacionalidad.getText());
            j.setIdEquipo((Integer) comboEquipo.getSelectedItem());

            // 2. Llamamos al DAO
            JugadorDAO dao = new JugadorDAO();
            if (dao.insertar(j)) {
                JOptionPane.showMessageDialog(this, "Jugador fichado con exito");
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar en BD.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El dorsal debe ser un número.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
